
UNIQUE_INGREDIENTS = {
    'pure peppermint extract': {"health": 6, "taste": 7},
    'almond butter': {"health": 8, "taste": 8},
    'almond flour': {"health": 9, "taste": 7},
    'applesauce': {"health": 8, "taste": 7},
    'baking powder': {"health": 3, "taste": 5},
    'baking soda': {"health": 3, "taste": 4},
    'brown sugar': {"health": 4, "taste": 8},
    'butter': {"health": 4, "taste": 9},
    'canned pumpkin': {"health": 9, "taste": 6},
    'chocolate bar of choice': {"health": 6, "taste": 10},
    'chocolate chips': {"health": 5, "taste": 10},
    'chopped nuts': {"health": 8, "taste": 7},
    'cinnamon': {"health": 7, "taste": 8},
    'cocoa powder': {"health": 8, "taste": 8},
    'coconut flour': {"health": 8, "taste": 6},
    'coconut oil': {"health": 6, "taste": 9},
    'coconut sugar': {"health": 7, "taste": 7},
    'cream cheese': {"health": 4, "taste": 8},
    'dutch cocoa powder': {"health": 8, "taste": 8},
    'egg': {"health": 8, "taste": 7},
    'finely chopped almonds': {"health": 8, "taste": 7},
    'finely chopped walnuts': {"health": 8, "taste": 7},
    'finely ground almond flour': {"health": 9, "taste": 7},
    'freeze-dried raspberries': {"health": 9, "taste": 6},
    'hazelnuts': {"health": 8, "taste": 7},
    'honey': {"health": 6, "taste": 8},
    'lemon juice': {"health": 7, "taste": 6},
    'maple syrup': {"health": 6, "taste": 9},
    'mashed banana': {"health": 9, "taste": 7},
    'melted coconut oil': {"health": 6, "taste": 9},
    'melted vegan butter': {"health": 5, "taste": 8},
    'milk of choice': {"health": 6, "taste": 7},
    'nut butter': {"health": 7, "taste": 8},
    'oat flour': {"health": 8, "taste": 7},
    'oats': {"health": 9, "taste": 7},
    'oil': {"health": 5, "taste": 9},
    'peanut butter': {"health": 7, "taste": 9},
    'powdered erythritol': {"health": 5, "taste": 5},
    'powdered sugar': {"health": 3, "taste": 8},
    'protein powder': {"health": 7, "taste": 6},
    'pumpkin pie spice': {"health": 6, "taste": 8},
    'pure maple syrup': {"health": 6, "taste": 9},
    'pure vanilla': {"health": 5, "taste": 7},
    'pure vanilla extract': {"health": 5, "taste": 7},
    'regular sugar': {"health": 3, "taste": 9},
    'rolled oats': {"health": 9, "taste": 7},
    'salt': {"health": 3, "taste": 9},
    'salted butter': {"health": 4, "taste": 9},
    'shredded coconut': {"health": 7, "taste": 8},
    'spelt flour': {"health": 8, "taste": 7},
    'tahini': {"health": 8, "taste": 7},
    'uncut stevia': {"health": 6, "taste": 5},
    'unsweetened shredded coconut': {"health": 7, "taste": 8},
    'vegan butter': {"health": 5, "taste": 8},
    'vegetable oil': {"health": 5, "taste": 9},
    'white flour': {"health": 3, "taste": 7},
    'white sugar': {"health": 3, "taste": 9}
}

LIQUIDS = [
    'pure peppermint extract', 'coconut oil', 'honey', 'lemon juice', 
    'maple syrup', 'melted coconut oil', 'melted vegan butter', 
    'milk of choice', 'oil', 'pure maple syrup', 'pure vanilla', 
    'pure vanilla extract', 'vegetable oil'
]

SOLIDS = [
    'almond butter', 'almond flour', 'applesauce', 'baking powder', 
    'baking soda', 'brown sugar', 'butter', 'canned pumpkin', 
    'chocolate bar of choice', 'chocolate chips', 'chopped nuts', 
    'cinnamon', 'cocoa powder', 'coconut flour', 'coconut sugar', 
    'cream cheese', 'dutch cocoa powder', 'egg', 'finely chopped almonds', 
    'finely chopped walnuts', 'finely ground almond flour', 
    'freeze-dried raspberries', 'hazelnuts', 'mashed banana', 
    'nut butter', 'oat flour', 'oats', 'peanut butter', 
    'powdered erythritol', 'powdered sugar', 'protein powder', 
    'pumpkin pie spice', 'regular sugar', 'rolled oats', 
    'salt', 'salted butter', 'shredded coconut', 'spelt flour', 
    'tahini', 'uncut stevia', 'unsweetened shredded coconut', 
    'vegan butter', 'white flour', 'white sugar'
]